name: Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php_version: '8.0'
          - php_version: '8.1'
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f php-${{ matrix.php_version }}/Dockerfile .

  use:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php_version: '8.0'
          - php_version: '8.1'
    steps:
      - uses: actions/checkout@v3
      - uses: ./